id: ans.fhir.fr.example
canonical: http://hl7.org/fhir/fr/example
name: ExampleIG
title: ANS IG Example
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

