# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.example
canonical: http://hl7.org/fhir/fr/example
name: ExampleIG
title: ANS IG Example
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        st_flux1.md:
            title: Flux 01
        st_flux2.md:
            title: Flux 02
    specifications_fonctionnelles.md:
        sf_ajout.md:
            title: Fonctionnalité 1
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages


menu:
  Accueil: index.html
  Spécifications techniques:
      Construction des flux: construction_des_flux.html
      Flux 01: st_flux1.html
      Flux 02: st_flux2.html
  Spécifications fonctionnelles:
      Spécifications fonctionnelles: specifications_fonctionnelles.html
      Fonctionnalité 1: sf_ajout.html
  Autres ressources:
      Sécurité: securite.html
      Téléchargements et usage: downloads.html
  Ressources extérieures:
      "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
      "ANS website ": new-tab https://esante.gouv.fr/