# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.example
canonical: https://interop.esante.gouv.fr/ig/fhir/example
name: ExampleIG
title: ANS IG Example
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        st_flux1.md:
            title: Flux 01
        st_flux2.md:
            title: Flux 02
    # specifications_fonctionnelles.md:
    #     sf_ajout.md:
    #         title: Fonctionnalité 1
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages

    tests.md:
        title: Tests      
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Description des flux:
        Construction des flux: construction_des_flux.html
        Flux 01: st_flux1.html
        Flux 02: st_flux2.html
    # Spécifications fonctionnelles:
    #     Spécifications fonctionnelles: specifications_fonctionnelles.html
    #     Fonctionnalité 1: sf_ajout.html
    Ressources de conformance: artifacts.html
    Tests:   tests.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html